#ifndef LEXER_H
#define LEXER_H

#include <stdint.h>
#include "allocator.h"
#include "source.h"

typedef enum: uint32_t {
#define TOKEN_TYPE(type) TokenType_ ## type
	TOKEN_TYPE(NO) = 0,
	TOKEN_TYPE(LSPE),
	TOKEN_TYPE(RSPE),
	TOKEN_TYPE(COM),
	TOKEN_TYPE(ID),
	TOKEN_TYPE(Q),
	TOKEN_TYPE(LR),
	TOKEN_TYPE(R),
	TOKEN_TYPE(RSCOPE),
	TOKEN_TYPE(L),
	TOKEN_TYPE(LSCOPE),
	TOKEN_TYPE(PL),
	TOKEN_TYPE(LIT),
	TOKEN_TYPE(COLON_LONELY),
#undef TOKEN_TYPE
} TokenType;

typedef enum: uint32_t {
#define TOKEN_SUBTYPE(subtype) TokenSubtype_ ## subtype
	TOKEN_SUBTYPE(NO) = 0,
	TOKEN_SUBTYPE(MODULE_INPUT),
	TOKEN_SUBTYPE(MODULE_OUTPUT),
	TOKEN_SUBTYPE(SCOPE),
	TOKEN_SUBTYPE(IF),
	TOKEN_SUBTYPE(ELSE_IF),
	TOKEN_SUBTYPE(ELSE),
	// litteral
	TOKEN_SUBTYPE(LIT_NUM), // the base is the highest byte
	TOKEN_SUBTYPE(LIT_CHAR),
	TOKEN_SUBTYPE(LIT_STR),
	// special
	TOKEN_SUBTYPE(EXCLAMATION_MARK),
	TOKEN_SUBTYPE(DQUOTES),
	TOKEN_SUBTYPE(HASH),
	TOKEN_SUBTYPE(MODULO),
	TOKEN_SUBTYPE(AMPERSAND),
	TOKEN_SUBTYPE(SQUOTE),
	TOKEN_SUBTYPE(LPARENTHESIS),
	TOKEN_SUBTYPE(RPARENTHESIS),
	TOKEN_SUBTYPE(ASTERISK),
	TOKEN_SUBTYPE(PLUS),
	TOKEN_SUBTYPE(COMMA),
	TOKEN_SUBTYPE(MINUS),
	TOKEN_SUBTYPE(PERIOD),
	TOKEN_SUBTYPE(DIVIDE),
	TOKEN_SUBTYPE(COLON),
	TOKEN_SUBTYPE(SEMICOLON),
	TOKEN_SUBTYPE(LOBRACKET),
	TOKEN_SUBTYPE(EQUAL),
	TOKEN_SUBTYPE(ROBRACKET),
	TOKEN_SUBTYPE(QUESTION_MARK),
	TOKEN_SUBTYPE(AT),
	TOKEN_SUBTYPE(LBRACKET),
	TOKEN_SUBTYPE(RBRACKET),
	TOKEN_SUBTYPE(BACKSLASH),
	TOKEN_SUBTYPE(CARET),
	TOKEN_SUBTYPE(UNDERSCORE),
	TOKEN_SUBTYPE(GRAVE_ACCENT),
	TOKEN_SUBTYPE(LCBRACE),
	TOKEN_SUBTYPE(RCBRACE),
	TOKEN_SUBTYPE(PIPE),
	TOKEN_SUBTYPE(TILDE),
#undef TOKEN_SUBTYPE
} TokenSubtype;

typedef struct {
	uint32_t type;
	uint32_t subtype;
	long int start;
	long int end;
} Token;

typedef struct {
	const Source* source;
	MemoryArea tokens;
} Lexer;

void initialize_lexer(Lexer* lexer);
bool create_lexer(
	const Source* source,
	MemoryArea* restrict memArea,
	Lexer* lexer);
void destroy_lexer(Lexer* lexer);

#endif
